### ISSUE TITLE
pull access denied

### ISSUE THREAD

**Issue by kumuji** [dusty-nv/jetson-containers#1]
Pull access denied for nvcr.io/nvidia-l4t-base, repository does not exist or may require 'docker login' denied: requested access to the resource is denied

Is it possible to pull the image?

**Comment by dusty-nv** [comment]
@kumuji sorry about that, the proper URL should be:  `nvcr.io/nvidia/l4t-base:r32.4.2`

Just fixed this in commit [`280887`](https://github.com/dusty-nv/jetson-containers/commit/280887a411e2dce5db16178a0dd41ad9878302b6).  Can you re-pull and try again?

**Comment by kumuji** [comment]
Sure, I am building it right now. Seems fine
