### ISSUE TITLE
NvInfer.h is empty.

### ISSUE THREAD

**Issue by hakuturu583** [dusty-nv/jetson-containers#119]
I tested jetson containers and I found that ./include/aarch64-linux-gnu/NvInfer.h is empty.
![Screenshot from 2022-01-04 00-17-44](https://user-images.githubusercontent.com/10348912/147947838-ab59e104-1b4f-42aa-810c-02e7b144f5f7.png)

Is it a right behavior?

**Comment by dusty-nv** [comment]
Hi @hakuturu583 sorry for the delay, do you have TensorRT installed on your device (outside of container)?   It gets mounted into the container at runtime.   It should have been installed by SDK Manager when you flashed the device, or if you are using an SD card image (for Nano or NX) it should already be installed.

**Comment by hakuturu583** [comment]
Thank you!
I will try!

**Comment by IGR2014** [comment]
Hello, I have same issue. And yes, outside the container NvInfer.h file is ok. Also, file date differs on docker/host
