### ISSUE TITLE
old dockers ?

### ISSUE THREAD

**Issue by an99990** [dusty-nv/jetson-containers#128]
Hi, so I am using docker dusty/galactic-pytorch-l4t-r32.6.1, and i noticed that thre some missing packages ?
I am not able to to `sudo apt-get install ros-galactic-diagnostic-updater `, or` sudo apt-get install ros-galactic-xacro `?

Is it normal ? I was able to build packages from source but why isnt it available inside the ros2 docker ?

thank you

**Comment by dusty-nv** [comment]
Hi @an99990, there aren't any apt packages for foxy/galactic for 18.04, and these containers are based on Ubuntu 18.04 (same as JetPack 4.x).  Hence all packages are built from source.

**Comment by an99990** [comment]
oh i understand, thank you for the prompt answer
