### ISSUE TITLE
Base image not found

### ISSUE THREAD

**Issue by CourchesneA** [dusty-nv/jetson-containers#155]
It seems [a recent commit ](https://github.com/dusty-nv/jetson-containers/commit/807641387dff89f5c30b4513fad740877521a29c) modified the $BASE_IMAGE variable in `docker_base.sh` to allow x86 support, but it breaks ros builds for me.

Specifically on r34.1.1 when I try to build using `test`, the $BASE_IMAGE gets set to `jetpack:r34.1.1` as per [this line](https://github.com/dusty-nv/jetson-containers/blob/be0dca3d19b30e64d129c92e93425c9ede40d65f/scripts/docker_base.sh#L36)
and then throws an error since the image does not exist.

I am not sure why this change was made in the first place so I won't offer a PR, but as a work around just commenting out the line solves the problem for me. I guess the variable $BASE_IMAGE is being migrated to $BASE_IMAGE_L4T ? In that case we might want to do the change in the build scripts too.

**Comment by dusty-nv** [comment]
Hi @CourchesneA, if you are on JetPack 5.0 / R34.1, then you should run `scripts/docker_build_jetpack.sh` first

**Comment by CourchesneA** [comment]
That is what I was missing, thanks !
