### ISSUE TITLE
It says package not found after source /opt/ros/foxy/install/setup.bash, how can I solve this problem?

### ISSUE THREAD

**Issue by leeyunhome** [dusty-nv/jetson-containers#162]
Hello, @dusty-nv 

Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
---
Finished <<< topic_service_action_rclpy_example [5.48s]

Summary: 13 packages finished [18.5s]

I built the package with the colcon build --symlink-install command.
It says package not found after source /opt/ros/foxy/install/setup.bash, how can I solve this problem?

Thank you.

**Comment by enricosutera** [comment]
What do you mean? You should source the workspace, not ros. 
Where did you use `colcon build --symlink-install `?

**Comment by leeyunhome** [comment]
Hello, @enricosutera 

in ~/robot_ws

Thank you.

**Comment by leeyunhome** [comment]
> What do you mean? You should source the workspace, not ros. Where did you use `colcon build --symlink-install `?

Hello, @enricosutera 

after source ~/robot_ws/install/local_setup.bash
![image](https://user-images.githubusercontent.com/59910227/174193369-559fef9f-9d1d-46fb-8c93-a8a8dac2d1eb.png)

Thank you.

**Comment by enricosutera** [comment]
You're welcome! I think you can close the issue yourself!
