### ISSUE TITLE
Running Ubuntu 18.04 L4T container in Jetpack 5 Ubuntu 20.04 and getting cuda to work

### ISSUE THREAD

**Issue by brianlmerritt** [dusty-nv/jetson-containers#168]
Hi Dusty,

Librealsense(2) doesn't have an ARM64 install yet for Ubuntu 20.04, but it does work with Ubuntu 18.04 and CUDA.  

So I am thinking about building an Ubuntu 18.04 Librealsense2/camera node with ROS Eloquent and networking that to the main host (which could be running docker or could be running native but in either case would be Ubuntu 20.04 based).

How do I link up L4T versions and/or CUDA versions so the 18.04 container accesses CUDA on the 20.04 host?

**Comment by dusty-nv** [comment]
> Librealsense(2) doesn't have an ARM64 install yet for Ubuntu 20.04

Hmm are you sure that you can't just build it from source on 20.04?

**Comment by brianlmerritt** [comment]
I guess I will have to try again thanks!  I've just seen big(ger) issues with sharing CUDA between 4.6 and 5.0 thanks you your forum answer.  If I get it working I will post a gist or similar here.

**Comment by andresgalaviz** [comment]
Hello @brianlmerritt, did you get it working? We're in the same position and currently exploring alternatives.

**Comment by brianlmerritt** [comment]
Been too busy - I plan to reflash my Jetson Xavier NX to 20.04 and try building from source over the holidays.
