### ISSUE TITLE
Getting 401 unauthorized when trying to pull images

### ISSUE THREAD

**Issue by nakai-omer** [dusty-nv/jetson-containers#186]
Tried a couple different images, all are returning `unauthorized: authentication required`

Via `sudo ./scripts/docker_build_ros.sh --distro humble`:
```
Step 1/34 : ARG BASE_IMAGE=nvcr.io/nvidia/l4t-base:r32.5.0
Step 2/34 : FROM ${BASE_IMAGE}
unauthorized: authentication required
```

Manual pull:
```
sudo docker pull nvcr.io/ea-linux4tegra/l4t-jetpack:r35.1.0
Error response from daemon: unauthorized: authentication required
```

Even trying to access the url manually in the browser causes a 401 error.

**Comment by dusty-nv** [comment]
Sorry about that @nakai-omer, just switched these to the public URLs in https://github.com/dusty-nv/jetson-containers/commit/0b6c72e0718f34f8f5ee53bf6e2a548809ac3c80

Please try pulling the latest from jetson-containers repo and try again

**Comment by nakai-omer** [comment]
wow you are the most amazing repo owner/maintainer ever!

**Comment by dusty-nv** [comment]
Haha thanks, happy to help!  👍
