### ISSUE TITLE
Can't install ROS2 Humble dependencies

### ISSUE THREAD

**Issue by nakai-omer** [dusty-nv/jetson-containers#188]
Hi, 

We are using the latest `dustynv/ros:humble-ros-base-l4t-r35.1.0` docker image as our base layer. 
When trying to install dependencies using rosdep we get the following error: 
```
#0 108.3 ERROR: the following packages/stacks could not have their rosdep keys resolved
#0 108.3 to system dependencies:
#0 108.3 nvblox_nav2: No definition of [nav2_costmap_2d] for OS version [focal]
#0 108.3 zed_wrapper: No definition of [xacro] for OS version [focal]
#0 108.3 zed_components: No definition of [diagnostic_updater] for OS version [focal]
#0 108.3 ira_laser_tools: No definition of [laser_geometry] for OS version [focal]
#0 108.3 coverage_path_planner: No definition of [nav2_core] for OS version [focal]
#0 108.3 nakai_robot: No definition of [tf_transformations] for OS version [focal]
#0 108.3 nvblox_rviz_plugin: No definition of [rviz_rendering] for OS version [focal]
```
We tried following the suggestion in this comment: https://github.com/dusty-nv/jetson-containers/issues/114#issuecomment-995372522 but it didn't help.

If we run rosdep install with `--os=ubuntu:jammy`, then we get the following error:
```
#0 104.1 ERROR: the following rosdeps failed to install
#0 104.1   apt: command [apt-get install -y ros-humble-rclcpp] failed
#0 104.1 executing command [apt-get install -y ros-humble-rclcpp]
`

**Comment by dusty-nv** [comment]
Hi @nakai-omer, I think what's going on is that the Humble debians packages in apt are for 22.04, but JetPack 5.0 is based on 20.04, so you may need to build those packages from source as opposed to trying to use rosdep to install them from debs.  

Here is an example of how I install additional ROS packages from source on top of a ROS distro in container:
https://github.com/dusty-nv/jetbot_ros/blob/d8e5ee1b17f5c66d038017b86f8920a496197ea9/Dockerfile#L72

Hope that helps,
Dusty

**Comment by nakai-omer** [comment]
@dusty-nv First of all, thanks for such quick responses all the time. 
It is going too hard to have to build every package from source, as all packages for humble are built for 22.04, as this is the humble's required OS. So, it means every single package we use, we will have to build from source. 
Are there any plans to support Ubuntu 22 on Jetpack anytime soon?

**Comment by dusty-nv** [comment]
Ubuntu 22 in JetPack is on the future horizon, but I can't give a definitive timeline - I think next year sometime.  

Also Humble doesn't "require" Ubuntu 22, but it's a tier-1 OS, meaning that the packages are already built for it:   https://docs.ros.org/en/foxy/Releases/Release-Humble-Hawksbill.html#supported-platforms
Ubuntu 20.04 is tier-3

If you try putting the package(s) that you want into `rosinstall_generator` like in that example I linked to, it should take care of the dependencies for you and also pull those in and build them - worth a shot.

**Comment by nakai-omer** [comment]
Ok i will try that thanks a lot

**Comment by nakai-omer** [comment]
@dusty-nv Unfortunately, rosinstall_generator also fails to recognize the packages:
```
The following unreleased packages/stacks will be ignored: ros-humble-diagnostic-updater, ros-humble-imu-tools, ros-humble-joint-state-publisher, ros-humble-laser-geometry, ros-humble-nav2-bringup, ros-humble-nav2-core, ros-humble-nav2-costmap-2d, ros-humble-nav2-msgs, ros-humble-nav2-util, ros-humble-pcl-ros, ros-humble-robot-localization, ros-humble-rosbridge-server, ros-humble-rviz-common, ros-humble-rviz-ogre-vendor, ros-humble-rviz-rendering, ros-humble-rviz2, ros-humble-slam-toolbox, ros-humble-tf-transformations, ros-humble-xacro
#13 23.48 No packages/stacks left after ignoring unreleased
```

This is our RUN command, which generically collects all the deps using rosdep:
```
RUN source ${ROS_ROOT}/install/setup.bash \
    && export ROS_PACKAGE_PATH=${AMENT_PREFIX_PATH} \
    && mkdir -p src/external_packages \
    && rosinstall_generator --deps --exclude RPP --rosdistro ${ROS_DISTRO} \
    `rosdep check --ignore-src --os=ubuntu:jammy --from-paths src | grep -oP 'ros-humble.*'` \
    > ros.${ROS_DISTRO}.external_packages.rosinstall \
    && vcs import src/external_packages < ros.${ROS_DISTRO}.external_packages.rosinstall 
```

**Comment by nakai-omer** [comment]
Posting what worked for us, just in case it will help someone:
```
# Install ROS2 deps
RUN source ${ROS_ROOT}/install/setup.bash \
    && export ROS_PACKAGE_PATH=${AMENT_PREFIX_PATH} \
    && mkdir -p src/external_packages \
    && rosinstall_generator --deps --exclude RPP --rosdistro ${ROS_DISTRO} \
    `rosdep keys --ignore-src --rosdistro=humble --from-paths src --skip-keys="PUT_DEPS_TO_SKIP_HERE"` \
    > ros.${ROS_DISTRO}.external_packages.rosinstall \
    && cat ros.${ROS_DISTRO}.external_packages.rosinstall \
    && vcs import src/external_packages < ros.${ROS_DISTRO}.external_packages.rosinstall 

RUN source ${ROS_ROOT}/install/setup.bash && apt-get update || true && rosdep update && rosdep install -y --skip-keys="PUT_DEPS_TO_SKIP_HERE" \
    --from-paths src --ignore-src -y --rosdistro=${ROS_DISTRO}
```

The `apt-get update || true ` is due to: https://forums.developer.nvidia.com/t/packages-are-not-synced/226954
but you can probably remove the `|| true` in the near future.

**Comment by Zeki411** [comment]
> Posting what worked for us, just in case it will help someone, it automatically detects the needed dependencies:
> 
> ```
> # Install ROS2 deps
> RUN source ${ROS_ROOT}/install/setup.bash \
>     && export ROS_PACKAGE_PATH=${AMENT_PREFIX_PATH} \
>     && mkdir -p src/external_packages \
>     && rosinstall_generator --deps --exclude RPP --rosdistro ${ROS_DISTRO} \
>     `rosdep keys --ignore-src --rosdistro=humble --from-paths src --skip-keys="PUT_DEPS_TO_SKIP_HERE"` \
>     > ros.${ROS_DISTRO}.external_packages.rosinstall \
>     && cat ros.${ROS_DISTRO}.external_packages.rosinstall \
>     && vcs import src/external_packages < ros.${ROS_DISTRO}.external_packages.rosinstall 
> 
> RUN source ${ROS_ROOT}/install/setup.bash && apt-get update || true && rosdep update && rosdep install -y --skip-keys="PUT_DEPS_TO_SKIP_HERE" \
>     --from-paths src --ignore-src -y --rosdistro=${ROS_DISTRO}
> ```
> 
> The `apt-get update || true ` is due to: https://forums.developer.nvidia.com/t/packages-are-not-synced/226954 but you can probably remove the `|| true` in the near future.

Thank you, this helps me a lot.

**Comment by JTShuai** [comment]
> Posting what worked for us, just in case it will help someone, it automatically detects the needed dependencies:
> 
> ```
> # Install ROS2 deps
> RUN source ${ROS_ROOT}/install/setup.bash \
>     && export ROS_PACKAGE_PATH=${AMENT_PREFIX_PATH} \
>     && mkdir -p src/external_packages \
>     && rosinstall_generator --deps --exclude RPP --rosdistro ${ROS_DISTRO} \
>     `rosdep keys --ignore-src --rosdistro=humble --from-paths src | egrep -v "PKG_2_SKIP1|PKG_2_SKIP2"` \
>     > ros.${ROS_DISTRO}.external_packages.rosinstall \
>     && cat ros.${ROS_DISTRO}.external_packages.rosinstall \
>     && vcs import src/external_packages < ros.${ROS_DISTRO}.external_packages.rosinstall 
> 
> RUN source ${ROS_ROOT}/install/setup.bash && apt-get update || true && rosdep update && rosdep install -y --skip-keys="PUT_DEPS_TO_SKIP_HERE" \
>     --from-paths src --ignore-src -y --rosdistro=${ROS_DISTRO}
> ```
> 
> The `apt-get update || true ` is due to: https://forums.developer.nvidia.com/t/packages-are-not-synced/226954 but you can probably remove the `|| true` in the near future.

@nakai-omer @dusty-nv 
Thanks! I'm quite new to ros2 and Jetson. I want to install diagnostic_updater, so I wrote a .sh file with these lines:
```shell
#!/bin/bash

set -e

source ${ROS_ROOT}/install/setup.bash

# 设置ROS_PACKAGE_PATH
export ROS_PACKAGE_PATH=${AMENT_PREFIX_PATH}

mkdir -p src/diagnostic_updater

# 生成rosinstall文件
rosinstall_generator --deps --exclude RPP --rosdistro ${ROS_DISTRO} \
    `rosdep keys --ignore-src --rosdistro=humble --from-paths src --skip-keys="PUT_DEPS_TO_SKIP_HERE"` \
    > ros.${ROS_DISTRO}.diagnostic_updater.rosinstall

cat ros.${ROS_DISTRO}.diagnostic_updater.rosinstall

vcs import src/diagnostic_updater < ros.${ROS_DISTRO}.diagnostic_updater.rosinstall

source ${ROS_ROOT}/install/setup.bash

apt-get update || true

rosdep update
rosdep install -y --skip-keys="PUT_DEPS_TO_SKIP_HERE" --from-paths src --ignore-src -y --rosdistro=${ROS_DISTRO}
```

But I got an error after running it: 
```shell
usage: rosinstall_generator [-h] [--debug] [--verbose] [--rosdistro ROSDISTRO]
                            [--from-path [FROM_PATH [FROM_PATH ...]]]
                            [--repos [reponame [reponame ...]]]
                            [--upstream | --upstream-development]
                            [--deps | --deps-up-to [DEPS_UP_TO [DEPS_UP_TO ...]]]
                            [--deps-depth N] [--deps-only]
                            [--wet-only | --dry-only | --catkin-only | --non-catkin-only]
                            [--exclude [EXCLUDE [EXCLUDE ...]]]
                            [--exclude-path [EXCLUDE_PATH [EXCLUDE_PATH ...]]]
                            [--flat] [--tar] [--format {rosinstall,repos}]
                            [pkgname [pkgname ...]]
rosinstall_generator: error: Either some package names must be specified, some --from-path or some repository names using --repos
```
Could you please help me point out my mistake in the script?
