### ISSUE TITLE
ROS2 - Humble on Jetson AGX Xavier L4T R35.2.1

### ISSUE THREAD

**Issue by htex0189** [dusty-nv/jetson-containers#224]
Hi,

Is it possible to build ROS2 via docker for L4T R35.2.1. 
I see current image is for R35.1.0. So only option is to downgrade to R35.1.0 on Jetson AGX, or is there any other options?

**Comment by dusty-nv** [comment]
@htex0189 I'm working on building these ROS/ROS2 container images for R35.2.1 now

**Comment by dusty-nv** [comment]
@htex0189 in the meantime you can run R35.1.0 containers on R35.2.1 without issue
