### ISSUE TITLE
Dockerfile for Ros-Humble-desktop with PyTorch

### ISSUE THREAD

**Issue by Fibo27** [dusty-nv/jetson-containers#247]
Hi @dusty-nv, as discussed in #244, i built a container using /scripts/docker_build_ros.sh --distro humble --package desktop --with-pytorch
The container was built and everything works well, except for two aspects:

1. The launch file is missing the codec command as highlighted in #244 - I know the workaround and presume that will have to commit to save the changes in the container.
2. The inferencing using the libraries in jetson-inference does not seem to work. I tried the ros deep-learning command (which is the same as how i had been running successfully without the container) - I get this message: "failed to find model manifest file 'networks/models.json'. 

- I checked inside the jetson-inference folder (in the container) and tried running the same model (inside /python/examples folder) using `./imagenet.py /dev/video0 ` with my USB camera - it gave the same result and the outcome does not change if i try out other models. (Note that this set-up works fine if I were to use the jetson-inference folder natively.)
- While comparing the jetson-inference folder within the container versus without a container, I find that the "data" folder inside jetson-inference folder is missing in the case of the former. 
- An error also comes up if i try to reload the models inside the container by `cd jetson-inference/tools` and then running `./download-models.sh`. 
- I then created a /data/networks folder inside jetson-inference folder of the container. This time the models are downloaded but when i try to run the inferencing program, i get the same error.

I am not sure what exactly is going on. Note that aside from inferencing, the rest of ROS modules, such as RViz, seem to be working as expected.
As a workaround, how can I use your existing container in NGC which, as you mentioned earlier in your response, is based on the ROS-base package and then upgrade it to desktop? Please note that I would want ROS-humble-desktop with pytorch and ros_deep_learning.

Thanks

**Comment by dusty-nv** [comment]
@Fibo27 can you try cloning jetson-inference to your device (outside of container) and then when you run ros_deep_learning's docker/run.sh, mount the jetson-inference/data dir:

``` bash
cd ros_deep_learning
docker/run.sh -v /path/to/jetson-inference/data:/jetson-inference/data
```
