### ISSUE TITLE
Not download models on llamaspeak

### ISSUE THREAD

**Issue by johnnynunez** [dusty-nv/jetson-containers#299]
Hi @dusty-nv, I think that your path model is not indexed.
![image](https://github.com/dusty-nv/jetson-containers/assets/22727137/c04d60ff-993a-4aca-a8af-da659232652b)

pd: well, I download it manually, but i get another error.
![image](https://github.com/dusty-nv/jetson-containers/assets/22727137/5a811cf1-7401-4f41-8b5a-70a3b725469d)

**Comment by johnnynunez** [comment]
.bin models are deprectated, use instead codellama-7b-.Q4_K_M.gguf

**Comment by dusty-nv** [comment]
Thanks @johnnynunez, yes I need to update the docs for llamaspeak.  Actually I am in the process of changing the LLM backend from oogabooga to MLC/TVM to get ~double the performance, and also integrate multimodality and Llava models.  Will update soon hopefully!

**Comment by johnnynunez** [comment]
> Thanks @johnnynunez, yes I need to update the docs for llamaspeak. Actually I am in the process of changing the LLM backend from oogabooga to MLC/TVM to get ~double the performance, and also integrate multimodality and Llava models. Will update soon hopefully!

Yes, It’s working nice with llama7b
![IMG_0115](https://github.com/dusty-nv/jetson-containers/assets/22727137/4069fffc-f852-4095-a269-9424792629e7)
