### ISSUE TITLE
MLC-LLM Missing Stream Iterator

### ISSUE THREAD

**Issue by amevec** [dusty-nv/jetson-containers#317]
Hardware: Orin AGX/NX
Software: dustynv/mlc:r35.4.1
Issue Summary: MLC-LLM has added an iterator for inference results which makes programmatically interfacing with the output easier not requiring capturing stdout

Resolution: Use updated mlc-llm main branch or apply commit manually to /usr/local/lib/python3.8/dist-packages/mlc_chat/callback.py
MLC-LLM pull request: https://github.com/mlc-ai/mlc-llm/pull/1057/
MLC-LLM commit for specific fix (to hotfix existing container): https://github.com/mlc-ai/mlc-llm/pull/1057/commits/c65659bf6064d48906844109341e04406953a56c

**Comment by dusty-nv** [comment]
Thanks @amevec, please see https://github.com/dusty-nv/jetson-containers/issues/316#issuecomment-1785336568
