### ISSUE TITLE
Doubt build pytorch

### ISSUE THREAD

**Issue by johnnynunez** [dusty-nv/jetson-containers#329]
Should we use export USE_CUDNN=1 to build Pytorch? @dusty-nv

**Comment by dusty-nv** [comment]
@johnnynunez cuDNN should be automatically detected by PyTorch and `USE_CUDNN=1` isn't explicitly needed.

If you're on JetPack 4, make sure the default docker runtime is nvidia and `DOCKER_BUILDKIT=0`

**Comment by johnnynunez** [comment]
thanks @dusty-nv
