### ISSUE TITLE
Guidanced Needed in Understanding and Downloading Correct Version of ONNXRUNTIME-GPU and CUDA

### ISSUE THREAD

**Issue by HShamimGEHC** [dusty-nv/jetson-containers#395]
I am still a beginner with jetson containers and am trying to understand things conceptually. 

I have docker image that is my own image that I want to run as a container utilizing the GPU on my Jetson AGX Xavier. For that, I need to modify the Dockerfile for the image to install Cuda and onnxruntime-gpu, whose versions should match and be compatible with the nvidia driver I have. 

It is my understanding that I cannot build the onnxruntime and cuda containers in this repo and use them for my image. So how can I ensure that I am downloading the right versions in the dockerfile for my image?

Guidance would greatly be appreciated. Thank you!

nvidia@ubuntu:~$ cat /etc/nv_tegra_release
R35 (release), REVISION: 4.1, GCID: 33958178, BOARD: t186ref, EABI: aarch64, DATE: Tue Aug  1 19:57:35 UTC 2023

nvidia@ubuntu:~/uswebapp/jetsonserver$ dpkg-query --show nvidia-l4t-core
nvidia-l4t-core 35.4.1-20230801124926

**Comment by dusty-nv** [comment]
@HShamimGEHC IIRC the onnxruntime dockerfile from this repo currently builds onnxruntime 1.16, however if it's easier for you the appropriate wheels for your environment can just be installed from https://elinux.org/Jetson_Zoo#ONNX_Runtime
