### ISSUE TITLE
Deepstream setup adjustments

### ISSUE THREAD

**Issue by Mark-Firestorm** [dusty-nv/jetson-containers#409]
When the python bindings are cloned they appear to be cloned in the wrong folder for being able to run the examples.  I'm not sure of the exact directory that the repo is supposed to be cloned in but it is one level deeper than it is currently.  

Proposed fix for this would be on [line 65](https://github.com/dusty-nv/jetson-containers/blob/8c013f71b1b6211260d5b685cd3ca4e7ccc875d0/packages/deepstream/Dockerfile#L65) of the Deepstream dockerfile, changing it to the following:

```
RUN cd /opt/nvidia/deepstream/deepstream/sources && \
```

Evidence for this being in the wrong place can be seen in the [config for deepstream_test1_usbcam](https://github.com/NVIDIA-AI-IOT/deepstream_python_apps/blob/36fdc7ef216d6c4255c6c5931f4adea6f1a1ef0a/apps/deepstream-test1-usbcam/dstest1_pgie_config.txt) where in the Deepstream folder structure, the sources folder being referenced for the model to be used is one level off in the current Docker environment.

Edit: corrected mistake in the proposed fix

**Comment by dusty-nv** [comment]
@Mark-Firestorm if you know this fix and could start submitting PRs for these that would be great, I will accept them.  Sorry been really busy, and don't have the time at the moment.

**Comment by Mark-Firestorm** [comment]
@dusty-nv I'll put together a fork and a PR now, thanks!

**Comment by Mark-Firestorm** [comment]
PR submitted

**Comment by dusty-nv** [comment]
Thanks Mark!  I merged your PR https://github.com/dusty-nv/jetson-containers/pull/411 into `dev`.  From there I will merge it into master 👍

**Comment by Mark-Firestorm** [comment]
Sure thing, thanks for the quick turn around!
