### ISSUE TITLE
About Temperature and Noise of Jetson Agx Orin 64G Processor

### ISSUE THREAD

**Issue by lq0104** [dusty-nv/jetson-containers#457]
This is a great project, and I would like to ask a question: what is the temperature of the Jetson Agx Orin 64G processor when running llamaspeak or other large language models, and is the noise level of the machine when running the program

**Comment by lq0104** [comment]
Because I think the level of noise is an important factor in human-computer interaction

**Comment by dusty-nv** [comment]
It does have a fan but I've rarely heard it, if ever.  The current temp running vision/language model shows 41C...it's not exactly like a PC, there are fanless/sealed embedded systems built for Jetson

**Comment by lq0104** [comment]
The sound is low, and the temperature is also very low. It's really cool! May I ask if your Jetson was assembled using a module by yourself or is it an official shelf product? Thank you very much for your answer

**Comment by dusty-nv** [comment]
It's just the devkit

**Comment by lq0104** [comment]
That's amazing! Thank you~
