### ISSUE TITLE
torch2trt build broken

### ISSUE THREAD

**Issue by hslr4** [dusty-nv/jetson-containers#502]
The torch2trt build fails since an update of torch2trt that removed `torch2trt/converters/interpolate.py`.

It seems to work again when lines 15 and 16 are removed from the corresponding Dockerfile here:
https://github.com/dusty-nv/jetson-containers/blob/ef2ef3e318f2911548af40f6bfccc9ab18c2daf4/packages/pytorch/torch2trt/Dockerfile#L15

Apperantly the problem this `sed` command fixed, is fixed in torch2trt itself since a previous commit: https://github.com/NVIDIA-AI-IOT/torch2trt/commit/f0520f0b32b2517b8d246537441f08bb5f245b55#diff-f34a4426e314e2b5c6097e416ede5acbe4abde50448ef570a2999783969c5189

**Comment by dusty-nv** [comment]
Thanks @hslr4, yes I am getting JP6 GA / L4T R35.3 setup now and will update the dockerfile for latest torch2trt 👍

**Comment by hslr4** [comment]
thanks 👍
