### ISSUE TITLE
Building ctranslate2 on AGX with JP5

### ISSUE THREAD

**Issue by budzianowski** [dusty-nv/jetson-containers#512]
Building with JP5 and 35.1.2 the ctranslate2 errors with https://github.com/OpenNMT/CTranslate2/issues/1664 
Have you managed to have successful builds lately or only with JP6 (higher cuda version).

**Comment by dusty-nv** [comment]
@budzianowski I believe I've only built it recently on JP6, and yea it builds flash-attention which requires newer CUDA.
