### ISSUE TITLE
exec error when using docker file

### ISSUE THREAD

**Issue by AWilson10** [dusty-nv/jetson-containers#52]
Hi, I tried to run the build script to build noetic (although it fails at the same place on any script).
I get this error:
standard_init_linux.go:211: exec user process caused "exec format error"
The command '/bin/sh -c apt-get update &&     apt-get install -y --no-install-recommends           git 		cmake 		build-essential 		curl 		wget 		gnupg2 		lsb-release     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 1

Can you explain why?
I tried running with sudo but no difference
One question, (and apologies for my docker newbie status) I am building on a x86 amd machine, could this be the issue? 
Do I have to create the image on a jetson?
Thanks

**Comment by dusty-nv** [comment]
> I am building on a x86 amd machine, could this be the issue?
Hi @AWilson10, yes these containers are meant to be built on Jetson.

**Comment by AWilson10** [comment]
Hi. I used this guide to emulate arm and it installed and run up ok on my x86 pc.
https://www.stereolabs.com/docs/docker/building-arm-container-on-x86/
