### ISSUE TITLE
Best practice for using ROS + ML/Vision stack?

### ISSUE THREAD

**Issue by lorepieri8** [dusty-nv/jetson-containers#53]
To setup both a ML/Vision stack (pytorch, librealsense, numpy, etc.) and a ROS stack (Noetic or ROS2) on the Jetson NX, what is the best practice? My understanding is that this repo presents separate docker containers for the ml stack and ROS.

Should I merge the dockerfiles of the ROS and ml stack container in this repo, or perhaps refer to https://github.com/dusty-nv/ros_deep_learning ?

**Comment by dusty-nv** [comment]
Hi @lorepieri8, I would change the BASE_IMAGE of the ROS containers to l4t-pytorch or l4t-ml here:

https://github.com/dusty-nv/jetson-containers/blob/c5303798b61101a9975e909319a5243d50175706/scripts/docker_build_ros.sh#L5

You may need to change that script around a little bit in how it sets the base image from the l4t version.
You should be able to use the pre-built l4t-pytorch on NGC (which would save you time).  It's URL/tag is just formed differently than l4t-base.  So you may want to skip those variables in the script and set it on this line instead:  https://github.com/dusty-nv/jetson-containers/blob/c5303798b61101a9975e909319a5243d50175706/scripts/docker_build_ros.sh#L19

**Comment by lorepieri8** [comment]
```
#!/usr/bin/env bash

set -e

BASE_IMAGE="nvcr.io/nvidia/l4t-ml"
L4T_VERSION="r32.4.4"
SUPPORTED_ROS_DISTROS=("melodic" "noetic" "eloquent" "foxy")
ROS_DISTRO=${1:-"all"}

echo "building containers for $ROS_DISTRO..."

if [[ "$ROS_DISTRO" == "all" ]]; then
	TO_BUILD=${SUPPORTED_ROS_DISTROS[@]}
else
	TO_BUILD=($ROS_DISTRO)
fi

for DISTRO in ${TO_BUILD[@]}; do
	sh ./scripts/docker_build.sh ros:$DISTRO-ros-base-l4t-$L4T_VERSION Dockerfile.ros.$DISTRO --build-arg BASE_IMAGE=$BASE_IMAGE:r32.4.4-py3
done
```

This worked for me.
