### ISSUE TITLE
Version tag/value not being passed into Ollama build

### ISSUE THREAD

**Issue by hillct** [dusty-nv/jetson-containers#559]
Upon deploying the jetson_containers Ollama docker image, and visiting http://localhost:11434/api/vrsion the return value is ```{"version": "0.0.0"}``` which reflects the fact that the version is no being injected to the build via the apparently preferred GOFLAGS method shown here https://github.com/ollama/ollama/blob/main/scripts/build_docker.sh#L5-L6

I would think the easiest way to inject it using the Jeson_Containers build framework, is to pass the value in via a docker build arg https://github.com/dusty-nv/jetson-containers/blob/master/packages/llm/ollama/Dockerfile
If I have some time this week I'll submit a fix, but if someone beats me to it, so much the better

**Comment by dusty-nv** [comment]
Thanks @hillct - fixed this in https://github.com/dusty-nv/jetson-containers/commit/6536834fae6b5a560ca68bb502e82a5204a83c7d and updated the docker images 👍

**Comment by hillct** [comment]
Tested on AGX Orin 32GB dev kit - confirmed operating as expected.
Thanks @dusty-nv
