### ISSUE TITLE
If some modules such as h5py is needed how can i add it to the container

### ISSUE THREAD

**Issue by MuhammedRishdhi123** [dusty-nv/jetson-containers#57]

**Comment by dusty-nv** [comment]
After you start the container, you will have a terminal prompt.  You can install the packages through the terminal, and then use [`docker commit`](https://docs.docker.com/engine/reference/commandline/commit/) to save your changes to a new container tag.

Alternatively, you can make your own Dockerfile where you use my container as your base image (using the `FROM` statement)

**Comment by MuhammedRishdhi123** [comment]
> After you start the container, you will have a terminal prompt. You can install the packages through the terminal, and then use [`docker commit`](https://docs.docker.com/engine/reference/commandline/commit/) to save your changes to a new container tag.
> 
> Alternatively, you can make your own Dockerfile where you use my container as your base image (using the `FROM` statement)

Thanks @dusty-nv  I was having trouble with that now it works fine !
