### ISSUE TITLE
Want to create a container that has got CUDA versions

### ISSUE THREAD

**Issue by dilerbatu** [dusty-nv/jetson-containers#599]
Hi Everyone,

I want to build image that will be my base image. This image should contain CUDA 11.4 CUDA 12.2 and also ros:noetic-desktop. I have tried to build this container a lot of times but it fails on the build.

Example Error
When I run this command : `jetson-containers build --name conv ros:noetic-desktop pytorch:2.1 cuda:12.2`

ERROR: Could not find a version that satisfies the requirement pip (from versions: none)
ERROR: No matching distribution found for pip
+ curl -sS https://bootstrap.pypa.io/pip/3.6/get-pip.py
+ python3.6
/tmp/install_python.sh: line 27: python3.6: command not found
curl: (23) Failed writing body (1338 != 1379)

Do you have any idea to create this container ?

Thanks.

**Comment by dusty-nv** [comment]
Hi @dilerbatu, it doesn't include multiple CUDA versions, and CUDA 12+ is only working on JetPack 6 or newer.  Sometimes you might also set CUDA_VERSION environment variable instead for better package resolution:   

https://github.com/dusty-nv/jetson-containers/blob/master/docs/build.md#changing-versions
