### ISSUE TITLE
Cannot install CUDA 12.1

### ISSUE THREAD

**Issue by dilerbatu** [dusty-nv/jetson-containers#600]
Hi All,

I want to install CUDA12.1 with my containers but it only installs cuda 11.4 each time when I write cuda:12.2

jetson-containers build --build-flags=--no-cache --name=cu122 cuda:12.2

EDIT: Now I can not install anything, each command gives me:

`
python3.8
Looking in indexes: http://jetson.webredirect.org/jp5/cu122
ERROR: Could not find a version that satisfies the requirement pip (from versions: none)
ERROR: No matching distribution found for pip
curl -sS https://bootstrap.pypa.io/pip/3.6/get-pip.py
python3.6
/tmp/install_python.sh: line 27: python3.6: command not found
curl: (23) Failed writing body (1338 != 1379)

`

**Comment by johnnynunez** [comment]
> Hi All,
> 
> I want to install CUDA12.1 with my containers but it only installs cuda 11.4 each time when I write cuda:12.2
> 
> jetson-containers build --build-flags=--no-cache --name=cu122 cuda:12.2
> 
> EDIT: Now I can not install anything, each command gives me:
> 
> ` python3.8 Looking in indexes: http://jetson.webredirect.org/jp5/cu122 ERROR: Could not find a version that satisfies the requirement pip (from versions: none) ERROR: No matching distribution found for pip curl -sS https://bootstrap.pypa.io/pip/3.6/get-pip.py python3.6 /tmp/install_python.sh: line 27: python3.6: command not found curl: (23) Failed writing body (1338 != 1379)
> 
> `

did you try with:
CUDA_VERSION=12.2 jetson-containers build cuda

**Comment by dilerbatu** [comment]
python issue just solved but it still installs cuda 11.4. I built the image with the command that u suggest. I run it but when I type nvcc --version, it gives 11.4.

**Comment by dusty-nv** [comment]
What JetPack are you on?  CUDA 12.2 is not on JetPack 5

**Comment by dilerbatu** [comment]
It explains everything, I guess. I am using Jetpack 5. Do I need to upgrade in order to use CUDA 12 ?

**Comment by dilerbatu** [comment]
It explains everything, I guess. I am using Jetpack 5. Do I need to upgrade in order to use CUDA 12 ?

**Comment by dilerbatu** [comment]
How will I install ros noetic If I use Jetpack 6 ? I kinda know that jetpack 6 works on ubuntu 22.04

**Comment by johnnynunez** [comment]
> It explains everything, I guess. I am using Jetpack 5. Do I need to upgrade in order to use CUDA 12 ? I am using Orin.

Yess, jetpack 6 is necessary
