### ISSUE TITLE
There is no preset of `OpenVLA-MimicGen-FP16` 

### ISSUE THREAD

**Issue by junh0cho** [dusty-nv/jetson-containers#602]
I am following tutorial of https://www.jetson-ai-lab.com/openvla.html

```
jetson-containers run $(autotag nano_llm) \
  python3 -m nano_llm.studio --load OpenVLA-MimicGen-FP16
```
Here `OpenVLA-MimicGen-FP16` is not available , along with `OpenVLA-MimicGen-FP8`, `OpenVLA-MimicGen-INT4`.
They seem to be available in https://github.com/dusty-nv/jetson-containers/tree/master/data/nano_llm/presets

**Comment by dusty-nv** [comment]
Ahh thank you @junh0cho, I had forgotten to merge these from the dev branch - here they are now in jetson-containers master:  https://github.com/dusty-nv/jetson-containers/commit/0d9e9a4d7f70841e03ed6fa9e71869bd7888b78b
