### ISSUE TITLE
openvla-7b-mimicgen along with OpenVLA-MimicGen-INT4  is around 0.9 FPS only

### ISSUE THREAD

**Issue by ericnien** [dusty-nv/jetson-containers#617]
I'm following https://www.jetson-ai-lab.com/openvla.html#__tabbed_1_1 to try the model.(openvla-7b-mimicgen) along with OpenVLA-MimicGen-INT4 on a Jetson AGX 60GB. I expected it should has ~2.9FPS. But it only has around 0.9. What should I do to increase to ~2.9FPS?

**Comment by ericnien** [comment]
It back to ~2.5 FPS when I changed power mode from 30W to MAXN. Is it safe to run in MAXN mode?

**Comment by johnnynunez** [comment]
> It back to ~2.5 FPS when I changed power mode from 30W to MAXN. Is it safe to run in MAXN mode?

yes

**Comment by dusty-nv** [comment]
Yes, like Johnny I use MAX-N 👍

________________________________
