### ISSUE TITLE
New Sota Open Source model LLM

### ISSUE THREAD

**Issue by johnnynunez** [dusty-nv/jetson-containers#619]
https://huggingface.co/mattshumer/Reflection-70B
https://x.com/mattshumer_/status/1831767014341538166

**Comment by johnnynunez** [comment]
new link: https://huggingface.co/mattshumer/Reflection-Llama-3.1-70B

**Comment by dusty-nv** [comment]
@johnnynunez this is a fine-tune of Llama-70B and should work though the existing quantization tools for deployment 👍
