### ISSUE TITLE
Why do jp6 containers include l4t-r36.2.0 as opposed to l4t-r36.3.0?

### ISSUE THREAD

**Issue by juliangaal** [dusty-nv/jetson-containers#630]
First, thanks for maintaining this extremely valuable repo!

According to the [release page](https://developer.nvidia.com/embedded/jetpack-sdk-60)

> JetPack 6.0 includes Jetson Linux 36.3

while your ros:humble images for jp6 are only available for `l4t-r36.2.0`. 

I can't seem to find where this specific version of l4t is set in your [gh actions file](https://github.com/dusty-nv/jetson-containers/blob/master/.github/workflows/ros-humble-ros-base_jp60.yml) or your python helper files. There only seem to be `get_jetpack()` functions, but none with `set_jetpack()` functionality.

My issue boils down to two questions:

a) where is the `l4t` version set in your build pipeline, and why is it set to `l4t-36.2.0`?
b) can I help you with regards to extending your repo with `l4t-36.3.0` support?

Cheers

**Comment by dusty-nv** [comment]
Hi, r36.2 containers are compatible with r36.3, so if I started building that container during 36.2, I keep it on 36.2 so there aren't extra tags floating around confusing at which is the latest.  New containers I start on 36.3.  It will tag it as what L4T you build it on, your you can override by setting L4T_VERSION environment variable.

________________________________
From: Julian Gaal ***@***.***>
Sent: Thursday, September 12, 2024 11:27:20 AM
To: dusty-nv/jetson-containers ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dusty-nv/jetson-containers] Why do jp6 containers include l4t-r36.2.0 as opposed to l4t-r36.3.0? (Issue #630)


First, thanks for maintaining this extremely valuable repo!

According to the release page<https://developer.nvidia.com/embedded/jetpack-sdk-60>

JetPack 6.0 includes Jetson Linux 36.3

while your ros:humble images for jp6 are only available for l4t-r36.2.0.

I can't seem to find where this specific version of l4t is set in your gh actions file<https://github.com/dusty-nv/jetson-containers/blob/master/.github/workflows/ros-humble-ros-base_jp60.yml> or your python helper files. There only seem to be get_jetpack() functions, but none with set_jetpack() functionality.

My issue boils down to two questions:

a) where is the l4t version set in your build pipeline?
b) can I help you with regards to extending your repo with l4t-36.3.0 support?

Cheers

**Comment by juliangaal** [comment]
ah, perfect, thank you!
