### ISSUE TITLE
Can we have vllm jetson images?

### ISSUE THREAD

**Issue by PredyDaddy** [dusty-nv/jetson-containers#635]
Hello Dusty,  Can I know if we will have the vllm jetson images?

**Comment by johnnynunez** [comment]
Super
https://x.com/_akhaliq/status/1836232050443006020?s=46

**Comment by PredyDaddy** [comment]
> Super https://x.com/_akhaliq/status/1836232050443006020?s=46

looks great! Can this vlm do open word object detection task?

**Comment by PredyDaddy** [comment]
Thanks~
