### ISSUE TITLE
dustynv/piper-tts:r35.4.1 container image seems broken

### ISSUE THREAD

**Issue by ark626** [dusty-nv/jetson-containers#686]
Jetson AGX Xavier with Jetpack 5.1.2 L4T 35.4.1 host

When running 
`jetson-containers run $(autotag piper-tts)`

It pulls an image and also starts it but there seems to be no piper in the piper-tts:r35.4.1-cuda container and also no Entrypoint.

 ```
ark626@ubuntu:/mnt/external/jetson-containers$ jetson-containers run $(autotag piper-tts)
 Namespace(disable=[''], output='/tmp/autotag', packages=['piper-tts'], prefer=['local', 'registry', 'build'], quiet=False, 
 user='dustynv', verbose=False)
-- L4T_VERSION=35.4.1  JETPACK_VERSION=5.1.2  CUDA_VERSION=12.6
-- Finding compatible container image for ['piper-tts']
piper-tts:r35.4.1-cuda
V4L2_DEVICES:
csi_indexes:
+ docker run --runtime nvidia -it --rm --network host --shm-size=8g --volume /tmp/argus_socket:/tmp/argus_socket --volume /etc/enctune.conf:/etc/enctune.conf --volume /etc/nv_tegra_release:/etc/nv_tegra_release --volume /tmp/nv_jetson_model:/tmp/nv_jetson_model --volume /var/run/dbus:/var/run/dbus --volume /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket --volume /var/run/docker.sock:/var/run/docker.sock --volume /mnt/external/jetson-containers/data:/data --device /dev/snd --device /dev/bus/usb --device /dev/i2c-0 --device /dev/i2c-1 --device /dev/i2c-2 --device /dev/i2c-3 --device /dev/i2c-4 --device /dev/i2c-5 --device /dev/i2c-6 --device /dev/i2c-7 --device /dev/i2c-8 -v /run/jtop.sock:/run/jtop.sock --name my_jetson_container_piper-tts_r35.4.1-cuda_20241015_141349 piper-tts:r35.4.1-cuda

```

When trying to build the container on Jetson AGX Xavier it fails too
[nohup.txt](https://github.com/user-attachments/files/17377957/nohup.txt)

**Comment by dusty-nv** [comment]
Hi @ark626 `piper-tts:r35.4.1-cuda` is an intermediate build stage on your device, not the final container.  Perhaps you started building it and it encountered an error or you otherwise stopped the build?   Can you try running `dustynv/piper-tts:r35.4.1` instead of  `piper-tts:r35.4.1-cuda`  ?

**Comment by dusty-nv** [comment]
The compiled source should be under `/opt/piper` and the wheel installed, so you should be able to do `python3 -c 'from piper import PiperVoice'` and run this [test script](https://github.com/dusty-nv/jetson-containers/blob/master/packages/speech/piper-tts/test.py) should you mount it in.

The Wyoming services that provide the HA container are built on top and found under these containers:  https://github.com/dusty-nv/jetson-containers/tree/master/packages/smart-home/wyoming
