### ISSUE TITLE
Cannot convert model file type using llama.cpp.

### ISSUE THREAD

**Issue by JIANGTUNAN** [dusty-nv/jetson-containers#703]
start command：
```shell
jetson-containers run $(autotag llama_cpp)
# The interaction pattern goes into the container
cd /opt/llama.cpp
python3 convert_hf_to_gguf.py
```
![image](https://github.com/user-attachments/assets/7c23f79a-828c-4447-b01b-e5c456c21909)

error message：
```shell
root@ubuntu:/opt/llama.cpp# python3 convert_hf_to_gguf.py
Traceback (most recent call last):
  File "/opt/llama-cpp-python/vendor/llama.cpp/convert_hf_to_gguf.py", line 20, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
```
![image](https://github.com/user-attachments/assets/33da4eac-c942-4ca8-ae3a-0ccb83d413ae)

I tried to install it manually：
```shell
root@ubuntu:/opt/llama.cpp# pip install torch torchvision torchaudio
root@ubuntu:/opt/llama.cpp# python3 -c "import torch; print(torch.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/torch/__init__.py", line 289, in <module>
    _load_global_deps()
  File "/usr/local/lib/python3.10/dist-packages/torch/__init__.py", line 245, in _load_global_deps
    raise err
  File "/usr/local/lib/python3.10/dist-packages/torch/__init__.py", line 226, in _load_global_deps
    ctypes.CDLL(global_deps_lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
```
![image](https://github.com/user-attachments/assets/05f61af4-967b-4997-a05b-bc8f26e1d51a)

I tried to use the conversion script from the `llama.cpp` project (`convert_hf_to_gguf.py`) and ran into problems converting model file types. I want to convert from `safetensors` to`gguf`. Is there any better advice? Be grateful for your help.![23453328](https://github.com/user-attachments/assets/5683afd1-1e7d-4a6d-a692-251d7d513671)

**Comment by johnnynunez** [comment]
@dusty-nv maybe needs: 
sudo apt install libopenmpi3
build of pytorch that didn't have it included.

**Comment by dusty-nv** [comment]
@JIANGTUNAN yes, in the container this:

```
apt-get update &&  \
apt-get install -y --no-install-recommends \
    libopenblas-dev \
    libopenmpi-dev \
    openmpi-bin \
    openmpi-common \
    gfortran \
    libomp-dev
```

@johnnynunez I had not been including PyTorch/ect in the llama.cpp build to keep it minimal.  However I see now that for the HF->GGUF conversion, it is needed.  In the future, by default I think I will rebase llama.cpp on pytorch image, and have a separate `llama.cpp:minimal` image without it.

**Comment by johnnynunez** [comment]
> @JIANGTUNAN yes, in the container this:
> 
> ```
> apt-get update &&  \
> apt-get install -y --no-install-recommends \
>     libopenblas-dev \
>     libopenmpi-dev \
>     openmpi-bin \
>     openmpi-common \
>     gfortran \
>     libomp-dev
> ```
> 
> @johnnynunez I had not been including PyTorch/ect in the llama.cpp build to keep it minimal. However I see now that for the HF->GGUF conversion, it is needed. In the future, by default I think I will rebase llama.cpp on pytorch image, and have a separate `llama.cpp:minimal` image without it.

Thank you dusty
