### ISSUE TITLE
base + tensorrt container?

### ISSUE THREAD

**Issue by turowicz** [dusty-nv/jetson-containers#77]
Can we please also get the `base` container with just `tensorrt` and it's dependencies installed?

**Comment by turowicz** [comment]
What I mean by this is that I want to be able to install a preferred python3 version.

**Comment by turowicz** [comment]
nevermind

**Comment by turowicz** [comment]
Actually this would be useful: binaries, static objects and source.

**Comment by dusty-nv** [comment]
l4t-base already has CUDA/cuDNN/TensorRT.  These get mounted in from the host with `--runtime nvidia`.   The version of TensorRT/CUDA/cuDNN needs to match what's in your version of JetPack-L4T.

**Comment by turowicz** [comment]
OK thank you
