### ISSUE TITLE
fatal error: helper_cuda.h: No such file or directory, when building Dockerfile.ros.slam

### ISSUE THREAD

**Issue by mvanlobensels** [dusty-nv/jetson-containers#82]
I get the following error when building the Dockerfile.ros.slam:

![image](https://user-images.githubusercontent.com/50023316/128707216-da0a8ca2-d440-44c7-b881-6a57468d4ece.png)

The error occurs when the following RUN command installs ORB_SLAM2_CUDA, which in turn executes the build.sh script:

![image](https://user-images.githubusercontent.com/50023316/128707596-64513ab2-b10e-4612-9d1c-f4e30af83884.png)

In the build scripts from ORB_SLAM2_CUDA, I tried including the missing file without much luck. Any help would be much appreciated!

**Comment by dusty-nv** [comment]
Hi @mvanlobensels, have you set your Docker default-runtime to nvidia?  https://github.com/dusty-nv/jetson-containers#docker-default-runtime

Also, can you run this command on your Jetson device (outside of container) to confirm you have `helper_cuda.h` on your system?

``` bash
$  find /usr -name 'helper_cuda.h'
/usr/local/cuda-10.2/samples/common/inc/helper_cuda.h
```

**Comment by mvanlobensels** [comment]
Hi @dusty-nv,

Yes, docker default-runtime is set to nvidia. I am building this on my own x86 laptop, which does not have CUDA installed. Should the `helper_cuda.h` file not be present inside the `nvcr.io/nvidia/l4t-base:r32.5.0` base image?

**Comment by mvanlobensels** [comment]
Is there a prebuilt docker image of the ros.foxy docker with SLAM available? Basically `./scripts/docker_build_ros.sh --distro foxy --with-slam`.

**Comment by dusty-nv** [comment]
> I am building this on my own x86 laptop

Ah, this is untested for x86, these containers are for Jetson.



> Is there a prebuilt docker image of the ros.foxy docker with SLAM available? Basically `./scripts/docker_build_ros.sh --distro foxy --with-slam`.

Yes, you can check the tags here:  https://hub.docker.com/repository/docker/dustynv/ros/tags?page=1&ordering=last_updated&name=slam
These are for Jetson/ARM64

**Comment by mvanlobensels** [comment]
Thank you! I somehow missed those. That will save me a lot of time.
